import type { AppState, Contractor, Lead } from "./types";

const daysAgo = (n: number, hour = 10) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
};

const daysAhead = (n: number, hour = 14) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
};

export const DEMO_CONTRACTORS: Contractor[] = [
  {
    id: "c-1",
    companyName: "Summit Roofing & Exteriors",
    contactName: "Dave Alvarez",
    email: "dave@summitroofing.com",
    password: "demo1234",
    phone: "(614) 555-0142",
    serviceTypes: ["Roofing", "Windows & Doors"],
    territoryZips: ["43004", "43016", "43017", "43026", "43081"],
    city: "Columbus, OH",
    active: true,
    createdAt: daysAgo(120),
  },
  {
    id: "c-2",
    companyName: "TrueTemp Heating & Air",
    contactName: "Marcy Whitfield",
    email: "marcy@truetemp.com",
    password: "demo1234",
    phone: "(614) 555-0188",
    serviceTypes: ["HVAC"],
    territoryZips: ["43004", "43081", "43230"],
    city: "Westerville, OH",
    active: true,
    createdAt: daysAgo(88),
  },
  {
    id: "c-3",
    companyName: "Buckeye Plumbing Co.",
    contactName: "Ron Kessler",
    email: "ron@buckeyeplumbing.com",
    password: "demo1234",
    phone: "(614) 555-0119",
    serviceTypes: ["Plumbing", "Bathroom Remodel"],
    territoryZips: ["43016", "43026", "43230"],
    city: "Hilliard, OH",
    active: false,
    createdAt: daysAgo(45),
  },
];

export const DEMO_LEADS: Lead[] = [
  {
    id: "l-1001",
    name: "Angela Brooks",
    phone: "(614) 555-2210",
    email: "angela.brooks@example.com",
    zip: "43017",
    serviceType: "Roofing",
    projectDetails:
      "Hail damage on the back slope, two visible leaks in the upstairs bedroom. Insurance adjuster already came out.",
    timeline: "Within 30 days",
    budget: "$12,000 - $20,000",
    isHomeowner: true,
    isDecisionMaker: true,
    status: "new",
    contractorId: "c-1",
    createdAt: daysAgo(0, 8),
    notes: [],
  },
  {
    id: "l-1002",
    name: "Terrence Hall",
    phone: "(614) 555-3391",
    email: "t.hall@example.com",
    zip: "43081",
    serviceType: "Roofing",
    projectDetails: "Full tear-off and replacement, 2,400 sq ft ranch. Wants architectural shingles.",
    timeline: "1-3 months",
    budget: "$18,000 - $25,000",
    isHomeowner: true,
    isDecisionMaker: true,
    status: "contacted",
    contractorId: "c-1",
    createdAt: daysAgo(2, 9),
    notes: [{ id: "n-1", body: "Left voicemail, texted quote link.", createdAt: daysAgo(1, 11) }],
  },
  {
    id: "l-1003",
    name: "Priya Raman",
    phone: "(614) 555-7745",
    email: "priya.r@example.com",
    zip: "43016",
    serviceType: "Roofing",
    projectDetails: "Gutter replacement plus soffit repair after storm. Two-story colonial.",
    timeline: "Within 30 days",
    budget: "$5,000 - $9,000",
    isHomeowner: true,
    isDecisionMaker: true,
    status: "qualified",
    contractorId: "c-1",
    createdAt: daysAgo(4, 13),
    notes: [{ id: "n-2", body: "Confirmed budget and ownership. Ready for site visit.", createdAt: daysAgo(3) }],
  },
  {
    id: "l-1004",
    name: "Michael Duarte",
    phone: "(614) 555-8820",
    email: "mduarte@example.com",
    zip: "43026",
    serviceType: "Windows & Doors",
    projectDetails: "Replacing 11 original windows, wants energy-efficient double pane.",
    timeline: "1-3 months",
    budget: "$14,000 - $18,000",
    isHomeowner: true,
    isDecisionMaker: true,
    status: "appointment",
    contractorId: "c-1",
    createdAt: daysAgo(6, 15),
    appointmentAt: daysAhead(3),
    notes: [{ id: "n-3", body: "In-home estimate scheduled, both spouses attending.", createdAt: daysAgo(2) }],
  },
  {
    id: "l-1005",
    name: "Sandra Lindqvist",
    phone: "(614) 555-6603",
    email: "s.lind@example.com",
    zip: "43004",
    serviceType: "Roofing",
    projectDetails: "Complete roof replacement after inspection failed during refinance.",
    timeline: "ASAP (emergency)",
    budget: "$16,000 - $22,000",
    isHomeowner: true,
    isDecisionMaker: true,
    status: "won",
    contractorId: "c-1",
    createdAt: daysAgo(18, 10),
    jobValue: 19400,
    notes: [{ id: "n-4", body: "Contract signed. Install week of the 12th.", createdAt: daysAgo(12) }],
  },
  {
    id: "l-1006",
    name: "Cody Reynolds",
    phone: "(614) 555-1177",
    email: "cody.r@example.com",
    zip: "43081",
    serviceType: "Roofing",
    projectDetails: "Small patch job on detached garage.",
    timeline: "3+ months / researching",
    isHomeowner: false,
    isDecisionMaker: false,
    status: "lost",
    contractorId: "c-1",
    createdAt: daysAgo(21, 16),
    notes: [{ id: "n-5", body: "Renter, not the decision maker. Disqualified.", createdAt: daysAgo(20) }],
  },
  {
    id: "l-1007",
    name: "Denise Okafor",
    phone: "(614) 555-4412",
    email: "denise.okafor@example.com",
    zip: "43017",
    serviceType: "Roofing",
    projectDetails: "Ridge vent install and attic ventilation assessment.",
    timeline: "Within 30 days",
    budget: "$3,000 - $6,000",
    isHomeowner: true,
    isDecisionMaker: true,
    status: "won",
    contractorId: "c-1",
    createdAt: daysAgo(30, 9),
    jobValue: 5200,
    notes: [],
  },
  {
    id: "l-2001",
    name: "Greg Sandoval",
    phone: "(614) 555-9081",
    email: "gsandoval@example.com",
    zip: "43230",
    serviceType: "HVAC",
    projectDetails: "22-year-old furnace short cycling. Wants full system replacement quote with AC.",
    timeline: "ASAP (emergency)",
    budget: "$8,000 - $12,000",
    isHomeowner: true,
    isDecisionMaker: true,
    status: "new",
    contractorId: "c-2",
    createdAt: daysAgo(0, 12),
    notes: [],
  },
  {
    id: "l-2002",
    name: "Hannah Weiss",
    phone: "(614) 555-2094",
    email: "hweiss@example.com",
    zip: "43081",
    serviceType: "HVAC",
    projectDetails: "Second floor never cools. Interested in mini-split addition.",
    timeline: "Within 30 days",
    budget: "$6,000 - $9,000",
    isHomeowner: true,
    isDecisionMaker: true,
    status: "appointment",
    contractorId: "c-2",
    createdAt: daysAgo(5, 11),
    appointmentAt: daysAhead(1, 10),
    notes: [],
  },
  {
    id: "l-2003",
    name: "Victor Nguyen",
    phone: "(614) 555-3350",
    email: "vnguyen@example.com",
    zip: "43004",
    serviceType: "HVAC",
    projectDetails: "Annual maintenance plan plus duct cleaning for a 4-bed home.",
    timeline: "1-3 months",
    isHomeowner: true,
    isDecisionMaker: true,
    status: "qualified",
    contractorId: "c-2",
    createdAt: daysAgo(9, 14),
    notes: [],
  },
  {
    id: "l-3001",
    name: "Rachel Kim",
    phone: "(614) 555-7788",
    email: "rachel.kim@example.com",
    zip: "43026",
    serviceType: "Bathroom Remodel",
    projectDetails: "Full primary bath gut renovation, walk-in tile shower.",
    timeline: "1-3 months",
    budget: "$25,000+",
    isHomeowner: true,
    isDecisionMaker: true,
    status: "new",
    contractorId: null,
    createdAt: daysAgo(1, 17),
    notes: [],
  },
  {
    id: "l-3002",
    name: "Owen Petrilli",
    phone: "(614) 555-6621",
    email: "owen.p@example.com",
    zip: "43230",
    serviceType: "Plumbing",
    projectDetails: "Main line backup, recurring twice this year. Needs camera inspection.",
    timeline: "ASAP (emergency)",
    isHomeowner: true,
    isDecisionMaker: true,
    status: "new",
    contractorId: null,
    createdAt: daysAgo(0, 15),
    notes: [],
  },
];

export const INITIAL_STATE: AppState = {
  contractors: DEMO_CONTRACTORS,
  leads: DEMO_LEADS,
  session: null,
};
